### ISSUE TITLE
Supreme Deathbringer Fairy freezes player

### ISSUE THREAD

**Issue by SaurabhTotey** [Fargowilta/FargowiltasSouls#139]
When equipping a Supreme Deathbringer Fairy, my player freezes and is unable to move or use items or do anything. This effect ends when the Supreme Deathbringer Fairy is then unequipped. This happens in both multiplayer and singleplayer. Below is a list of my installed mods.
* CalamityMod v1.4.2.107
* ThoriumMod v1.6.0.4
* SacredTools v1.1.0.9
* SpiritMod v1.3.5.4
* CalamityModMusic v1.4.2.1
* FargowiltasSouls v1.0.0
* AlchemistNPC v8.8.1
* BaseMod v1.9.0.1
* BossChecklist v0.2.1
* GRealm v1.9.0.1
* Fargowiltas v1.5
* imkSushisMod v4.3.1
* MagicStorage v0.4.3.5
* RecipeBrowser v0.8.4
* SummonersAssociation v0.4.2

#

Below is a stack trace from a log from me hosting and playing that I believe is relevant.

```
System.TypeLoadException: Could not load type 'CalamityMod.CPlayerUtils' from assembly 'CalamityMod_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at FargowiltasSouls.FargoPlayer.CalamityDamage(Single dmg)
   at FargowiltasSouls.FargoPlayer.AllDamageUp(Single dmg) in FargowiltasSouls\FargoPlayer.cs:line 3101
   at FargowiltasSouls.Items.Accessories.Masomode.SupremeDeathbringerFairy.UpdateAccessory(Player player, Boolean hideVisual) in FargowiltasSouls\Items\Accessories\Masomode\SupremeDeathbringerFairy.cs:line 62
   at Terraria.ModLoader.ItemLoader.UpdateAccessory(Item item, Player player, Boolean hideVisual)
   at Terraria.Player.VanillaUpdateAccessory(Int32 i, Item item, Boolean hideVisual, Boolean& flag, Boolean& flag2, Boolean& flag3)
   at Terraria.Player.UpdateEquips(Int32 i)
   at Terraria.Player.Update(Int32 i)
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)
   at Terraria.Main.DedServ()
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)
```

**Comment by Fargowilta** [comment]
Already fixed for next update
