### ISSUE TITLE
Soul of Yggdrasil makes character get stuck

### ISSUE THREAD

**Issue by LucoEldritch** [Fargowilta/FargowiltasSouls#199]
I was playing in a multiplayer world with many mods, including Thorium, Fargowiltas and Fargowiltas Souls, but I didn't play in some time, maybe a month.

When I joined today, both me and my friend couldn't move or do anything, and things like Probes from Pure Heart were not present. I tried reopening the server, with no avail, when my friend found out that removing Soul of Yggdrasil solved the problem.

Here's my modpack file (I changed to .txt so I could attach here on Github)
[ThoriumSpiritMaso.txt](https://github.com/Fargowilta/FargowiltasSouls/files/4366261/ThoriumSpiritMaso.txt)

When I was trying to look at the logs to find out specific mods versions, I found this:
```
[17:16:39] [1/WARN] [tML]: Silently Caught Exception: 
System.MissingFieldException: Field not found: 'ThoriumMod.ThoriumPlayer.folvSet'.
   at FargowiltasSouls.Items.Accessories.Forces.Thorium.VanaheimForce.UpdateAccessory(Player player, Boolean hideVisual)
   at FargowiltasSouls.Items.Accessories.Souls.ThoriumSoul.UpdateAccessory(Player player, Boolean hideVisual) in FargowiltasSouls\Items\Accessories\Souls\ThoriumSoul.cs:line 93
   at Terraria.ModLoader.ItemLoader.UpdateAccessory(Item item, Player player, Boolean hideVisual)
   at Terraria.Player.VanillaUpdateAccessory(Int32 i, Item item, Boolean hideVisual, Boolean& flag, Boolean& flag2, Boolean& flag3)
   at Terraria.Player.UpdateEquips(Int32 i)
   at Terraria.Player.Update(Int32 i)
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)
   at Terraria.Main.DedServ()
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)
```
Which could be related.

**Comment by Fargowilta** [comment]
fixed
